name: Black Box Testing

on: [push]

jobs:
  pytest-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker-Compose up
        working-directory: .
        run: docker-compose up --build

      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - run: pip install pytest requests

      - name: Docker PS
        run: docker ps

      - name: GitHub Action for pytest
        working-directory: ./tests
        run: bash -c 'sleep 30 && pytest'

      - name: Docker-Compose down
        working-directory: .
        run: docker-compose down
