name: Auto Deployment
on:
  push:
    branches:
      - master

jobs:
  Deployment-Backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd freshworksTesting
          echo "         project folder"
          git pull
          bash -c 'sleep 1'
          git checkout master
          git pull
          bash -c 'sleep 1'
          echo "before docker compose down"
          sudo docker-compose down
          bash -c 'sleep 30'
          sudo docker-compose up -d --build
          bash -c 'sleep 30'

  Deployment-Frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    needs: [Deployment-Backend]
    steps:
    - uses: actions/checkout@v1
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ll
          cd freshworksTesting
          echo "         project folder"
          git pull
          bash -c 'sleep 1'
          git checkout master
          git pull
          bash -c 'sleep 1'
          fuser -k -n tcp 3000
          npm run build
          bash -c 'sleep 30'
          serve -s build -n -l 3000 &
          bash -c 'sleep 30'
          echo "serve port 3000"
        wait-on: http://localhost:3000
